### ISSUE TITLE
Django Setup

### ISSUE THREAD

**Issue by Benohene** [Benohene/foundation-stone#1]
As a **Developer**, **I can set up Django and libraries**, so that **I can create apps to develop the site.**

## Acceptance Criteria

- Install Django and other libraries
- Check out the Django setup success page when running the server

## Task

- [ ] Django/Libraries Install.
- [ ] Install predicted libraries based on Boutique Ado Walkthrough
- [ ] Create a requirements.txt file
- [ ] Freeze requirements.txt file

**Comment by Benohene** [comment]
`python -m venv .virtual-environment-name` to install the virtual environment
`.virtual-environment-name/Scripts/activate` to activate the virtual environment to make installation of Django and dependencies

**Comment by Prettywierdo** [comment]
How do i set it up?

**Comment by Prettywierdo** [comment]
Where do i install django from??

**Comment by Prettywierdo** [comment]
So i should just type what you wrote in the comments into my python environment to create a virtual environment ?

**Comment by Prettywierdo** [comment]
So i should just type what you wrote in the comments into my python environment to create a virtual environment ?

**Comment by Prettywierdo** [comment]
After running myenv/Scripts/activate , it came up with error message

**Comment by Prettywierdo** [comment]
Ohh it finally worked . I copied the path from my own desktop and it's downloading now. Thank you so much for your help . I'm new to python and I'm just finding my way around it

**Comment by Benohene** [comment]
Ok. Good to hear that it worked out
