### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Benohene** [Benohene/foundation-stone#2]
As a User, I can **easily navigate between the site pages **, so that **I can find what I am looking for.**

### Acceptance Criteria

- Uniform navigation tabs on each page of the site

### Task

- [ ]  Create a site header
- [ ]  Create Hero section content with a Shop Now button to link all products
- [ ]  Create a footer with contact details with a social link

**Comment by Gurini** [comment]
Please for the homepage, is it just the backend setup or does it include the frontend as well

**Comment by Benohene** [comment]
@Gurini 
Actually there will be no backend for the homepage.  The backend will be more for the contact page and also attaching youtube videos
