### ISSUE TITLE
CONTACT US

### ISSUE THREAD

**Issue by Benohene** [Benohene/foundation-stone#4]
***
As a **User**, I can **contact details about the church**, so that **reach out for more information**.

## Acceptance Criteria
- User can contact the church for more information on the contact page

## Task
- [ ] Create a Contact Us page
- [ ] Create contact forms with validations
- [ ] Link to an Email to receive messages being sent.
- [ ] Send an automatic message with no reply when the message is sent successfully.
