### ISSUE TITLE
DONATION/GIVING PAGE

### ISSUE THREAD

**Issue by Benohene** [Benohene/foundation-stone#5]
## Sub-title

***
As a **User**, I can **visit the donation page**, so that **find details or click a button to donate money**.

## Acceptance Criteria
- Create a donation page that helps users to find details and ways to donate money

## Task
- [ ] Create a giving information section
- [ ] Create a Paypal link section
- [ ] Add Bank information
